<a href="https://colab.research.google.com/github/parikhdev/Google-Colaboratory/blob/main/Pytorch_BreastCancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
print(x_train)
y_train

[[ 2.64310404  1.71632964  2.78761403 ...  2.44832649  0.49445052
   0.2043698 ]
 [ 0.23553527  0.21976706  0.19322266 ... -0.18330776 -0.81214159
  -0.97613724]
 [-0.40781743  1.09083134 -0.41714944 ...  0.06666682 -0.09186102
   0.653541  ]
 ...
 [-0.65943982 -1.05902945 -0.62542807 ... -0.12349789 -0.44175661
   0.81399827]
 [ 0.08398997 -1.34166201  0.04403896 ... -0.07595671  0.28010007
  -1.26375962]
 [-0.6708772  -0.03506558 -0.70725182 ... -0.86253318  0.94994524
  -0.78020472]]

202    M
495    B
228    B
85     M
318    B
      ..
133    B
120    B
510    B
225    B
310    B
Name: diagnosis, Length: 455, dtype: object

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [11]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
print(x_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])

In [13]:
class MySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1],1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [14]:
learning_rate = 0.1
epochs = 25
model = MySimpleNN(x_train_tensor)
for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')
    model.bias

Epoch: 1, Loss: 3.6430281698755698
Epoch: 2, Loss: 3.5259359771331322
Epoch: 3, Loss: 3.40458379436379
Epoch: 4, Loss: 3.275221256697709
Epoch: 5, Loss: 3.1382613320597454
Epoch: 6, Loss: 2.9908149269541346
Epoch: 7, Loss: 2.8375933336038464
Epoch: 8, Loss: 2.672959220875678
Epoch: 9, Loss: 2.507464425863012
Epoch: 10, Loss: 2.342185283032177
Epoch: 11, Loss: 2.1743413001384044
Epoch: 12, Loss: 2.0004681914837086
Epoch: 13, Loss: 1.824293756630629
Epoch: 14, Loss: 1.652529227636155
Epoch: 15, Loss: 1.4901857029535883
Epoch: 16, Loss: 1.3362289552884838
Epoch: 17, Loss: 1.1976970930227868
Epoch: 18, Loss: 1.077428891578223
Epoch: 19, Loss: 0.9778227972920294
Epoch: 20, Loss: 0.9000860947477427
Epoch: 21, Loss: 0.8434149706479029
Epoch: 22, Loss: 0.8047284341458214
Epoch: 23, Loss: 0.7794970817083668
Epoch: 24, Loss: 0.7631864370298513
Epoch: 25, Loss: 0.752293391691282

In [26]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred >  0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5526315569877625